theme: jekyll-theme-leap-day
title: [Algebra Lineal y Machine Learning]
description: [Una breve descripcion de la necesidad de tener una minima base de algebra lineal, para poder encarar cuaqluier curso de machine learning.]
